services:

  app:
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - IS_DOCKER=TRUE
    depends_on:
      - postgres-db
    networks:
      - my-network

  postgres-db:
    image: postgres
    restart: always
    container_name: postgres-db
    volumes:
      - ./src/database/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
    networks:
      - my-network

networks:
  my-network:
    driver: bridge