services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DATABASE=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    networks:
      - my-network

  app:
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - postgres-db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db: